# Example bayesian.yaml entry
binary_sensor:
 - platform: bayesian
   # Starting probability
   prior: 0.1
   # Change to a name that suites your purpose
   name: "Bob Started Washer"
   # Threshold that activates this sensor
   probability_threshold: 0.95
   observations:
     - entity_id: "sensor.iBeacon"
       prob_given_true: 0.6
       prob_given_false: 0.2
       platform: "state"
       to_state: "laundry_rm"
     - platform: "state"
       entity_id: "sensor.washer_on"
       prob_given_true: 0.5
       prob_given_false: 0.4
       to_state: "on"
